name: Setup and Build

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        default: "Release"
      version:
        type: string
        default: ""
    secrets:
      token:
        required: false

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
      DALAMUD_ARCHIVE_URL: ${{ vars.DALAMUD_ARCHIVE_URL || 'https://goatcorp.github.io/dalamud-distrib/latest.zip' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.token || github.token }}
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Cache Dalamud
        uses: actions/cache@v5
        id: cache-dalamud
        with:
          path: ${{ env.DALAMUD_HOME }}
          key: dalamud-${{ env.DALAMUD_ARCHIVE_URL }}

      - name: Download Dalamud Latest
        if: steps.cache-dalamud.outputs.cache-hit != 'true'
        run: |
          wget ${{ env.DALAMUD_ARCHIVE_URL }} -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Build Project
        run: |
          BUILD_ARGS="--configuration ${{ inputs.configuration }} JobAutoSwitcher/JobAutoSwitcher.csproj"
          if [ -n "${{ inputs.version }}" ]; then
            BUILD_ARGS="$BUILD_ARGS -p:AssemblyVersion=${{ inputs.version }}"
          fi
          dotnet build $BUILD_ARGS

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v6
        with:
          name: JobAutoSwitcher
          retention-days: 14
          path: |
            JobAutoSwitcher/bin/${{ inputs.configuration }}/*
            !JobAutoSwitcher/bin/${{ inputs.configuration }}/JobAutoSwitcher/

      - name: Rename Release Asset
        if: inputs.version != ''
        run: mv JobAutoSwitcher/bin/${{ inputs.configuration }}/JobAutoSwitcher/latest.zip JobAutoSwitcher/bin/${{ inputs.configuration }}/JobAutoSwitcher/JobAutoSwitcher.zip

      - name: Upload Release Asset
        if: inputs.version != ''
        uses: actions/upload-artifact@v6
        with:
          name: JobAutoSwitcher-release
          retention-days: 1
          path: JobAutoSwitcher/bin/${{ inputs.configuration }}/JobAutoSwitcher/JobAutoSwitcher.zip
